Reducers: add default handler
piotrwitek/typesafe-actions pull request #241
Opened 2020-10-21 13:49 UTC by bunysae

## Description
Adds a defaultHandler for reducers

## Related issues:
- Resolved #156

## Checklist

* [X] I have read [CONTRIBUTING.md](https://github.com/piotrwitek/typesafe-actions/blob/master/CONTRIBUTING.md)
* [X] I have linked all related issues above
* [ ] I have rebased my branch

For bugfixes:
* [ ] I have added at least one unit test to confirm the bug have been fixed
* [ ] I have checked and updated TOC and API Docs when necessary

For new features:
* [X] I have added entry in TOC and API Docs
* [X] I have added a short example in API Docs to demonstrate new usage
* [ ] I have added type unit tests with `dts-jest`
* [ ] I have added runtime unit tests with `dts-jest`

2020-11-26 10:50 UTC, jalopez commented
Hi, do you have any news on this? I need this desperately. @piotrwitek could you please merge this?

2021-01-12 05:10 UTC, wi-ski commented
lol - i need this too!

2022-01-12 16:02 UTC, piotrwitek commented on src/create-reducer.spec.snap.ts
> +const reduxInit = createAction('@@redux/INIT.1')();
reduxInit cannot be handled as it is implementation details of Redux not a public API

2022-01-12 16:08 UTC, piotrwitek requested changes

2023-12-19 03:27 UTC, jin60641 commented
@piotrwitek 
Hi.
I have opened a new PR with the comments addressed, please review. Thanks
https://github.com/piotrwitek/typesafe-actions/pull/264

2024-01-06 18:32 UTC, piotrwitek commented
closed because it's stale

2024-01-06 18:32 UTC, closed without merging